### ISSUE TITLE
Erstellung eines neues Clients ohne client_id 

### ISSUE THREAD

**Issue by rdeutz** [mjaschen/collmex#1]
Es sieht so aus als könnte man keinen neuen Client über die API erzeugen:

Datenarray zur Erzeugung eines Clients:

`Array
(
    [firm] => FNAME
    [department] => dep1
    [forename] => Firstname
    [lastname] => Lastename
    [street] => Street
    [zipcode] => 132456
    [city] => City
    [email] => test@email.com
    [output_medium] => 1
    [inactive] => 0
    [country] => GB
    [client_id] => 
)`

Fehlermeldung:
**Firma 0 nicht vorhanden; Code=205000**

Es ist dabei uninteressant ob ich Client leer lasse, mit 0 definiere und auch -1 geht nicht. Lauf API sollte "-1" dazu führen das ein neuer Client angelegt wird. 

Die Frage wäre jetzt ist das ein Problem in dem Package oder in der API?

Viele Grüße
Robert

**Comment by mjaschen** [comment]
Hallo Robert,

du musst im Datensatz die "Firma Nr" angeben, damit Collmex weiß zu welcher Firma der Kunde gehört. Im Beispielcode ist es die erste Zeile des Datensatzes:

![.](https://dl.dropboxusercontent.com/s/1eib2e5e4nv2y0h/2016-04-18%20at%2010.23.png)

Diese Nummer findest du in Collmex unter "Verwaltung" → "Firma anzeigen und ändern".

**Comment by rdeutz** [comment]
Aso, jetzt geht das, schon etwas verwirrend.

Danke für die Erklärung!
