### ISSUE TITLE
Support for PHP 7.3

### ISSUE THREAD

**Issue by strausmann** [mjaschen/collmex#100]
Please add Support for PHP 7.3

**Comment by mjaschen** [comment]
Working on it, expect a release by tomorrow.

**Comment by mjaschen** [comment]
PHP ~7.3.0 was added to the list of supported PHP versions in the Composer config. 

Just update the Collmex lib to >= 0.10.0 and you're set.

**Comment by oliverklee** [comment]
I think this ticket can be closed now.
