### ISSUE TITLE
Renamed fields not in Tag 0.11

### ISSUE THREAD

**Issue by Argee88** [mjaschen/collmex#105]
- field names renamed in StockChange:
    - supplier_order_id → purchase_order_id
    - supplier_order_position → purchase_order_position

in ChangeLog, but when I switch to Tag 0.11.0 or 0.11.1 those fields still are supplier_order instead of purchase_order

**Comment by mjaschen** [comment]
I see it in 0.11.1: 

<https://github.com/mjaschen/collmex/blob/34d707d1fcdbf011a82eb7ea84641b5e3a3d3085/src/Type/StockChange.php#L79-L80>

**Comment by Argee88** [comment]
Okay, very strange... I checked it 4 times yesterday :D okay, never mind! sorry for that!
