### ISSUE TITLE
Update PHPUnit to Version 7.x

### ISSUE THREAD

**Issue by mjaschen** [mjaschen/collmex#112]
After changing the minimum required PHP version to 7.1 (#111), PHPUnit should be updated too. [PHPUnit 7.x](https://phpunit.de/getting-started/phpunit-7.html) is the highest version which supports PHP 7.1.

**Comment by oliverklee** [comment]
I can take care of this.

**Comment by mjaschen** [comment]
I suggest I give you commit rights - that would make things a little easier. Does that sound okay to you?

**Comment by oliverklee** [comment]
Yes, that sounds okay if you still are willing to review my PRs. (I'm a big proponent of peer review. And of automated tests. And of static code analysis.)

**Comment by mjaschen** [comment]
Yes, I'd definitively take a look at changes. After all, there is still my name in the library title ;-)
