### ISSUE TITLE
Fix the return type of ZipResponse::getCsvResponse

### ISSUE THREAD

**Issue by oliverklee** [mjaschen/collmex#124]
https://github.com/mjaschen/collmex/blob/master/src/Response/ZipResponse.php#L79

This method currently has an `InvalidNullableReturnType` annotation which I'd like to get rid of.

I propose to make the return type nullable and explicitly return null if the ZIP does not contain a CSV file.

@mjaschen What do you think?

**Comment by oliverklee** [comment]
@mjaschen I'll really appreciate you input on this before I start implementing.

**Comment by mjaschen** [comment]
According to the [API documentation](https://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,api_Rechnungen) Collmex PDF responses always contain the CSV file:

> Falls als Rückgabe-Format '1' gewählt wurde, gibt Collmex eine ZIP-Datei zurück. In dieser ZIP-Datei ist jede Rechnung im PDF-Format enthalten. Der Dateiname ist 'InvoiceXXXX.pdf', wobei XXXX die Rechnungsnummer ist. *In der ZIP-Datei sind zusätzlich die Rechnungen in der CSV-Datei result.csv im Format CMXINV enthalten.*

Maybe throwing an exception to notify about invalid response data would be a cleaner way to handle this. What do you think?

**Comment by oliverklee** [comment]
Sounds good. Then I'll do it that way. Thanks for your input!
