### ISSUE TITLE
Laravel 5 Service Provider

### ISSUE THREAD

**Issue by wh-im** [mjaschen/collmex#13]
@mjaschen Hallo Marcus, ein Update des Service Providers für Laravel 5.x wäre super, ist das geplant? Danke!

**Comment by mjaschen** [comment]
Hi,

ich werde einen einbauen.

Viele Grüße

Marcus

**Comment by wh-im** [comment]
Das sind super Nachrichten! Vielen Dank!

**Comment by wh-im** [comment]
Sorry, vielleicht machen wir die Issue besser zu, wenn es implementiert ist :)

**Comment by wh-im** [comment]
Sorry, vielleicht machen wir die Issue besser zu, wenn es implementiert ist,

**Comment by mjaschen** [comment]
Der Service Provider ist jetzt kompatibel zu Laravel 5.x.
