### ISSUE TITLE
Target [MarcusJaschen\Collmex\Client\ClientInterface] is not instantiable while building [MarcusJaschen\Collmex\Request].

### ISSUE THREAD

**Issue by arulananth** [mjaschen/collmex#153]
Target [MarcusJaschen\Collmex\Client\ClientInterface] is not instantiable while building [MarcusJaschen\Collmex\Request].

**Comment by mjaschen** [comment]
How can we help you?

**Comment by arulananth** [comment]
ClientInterface is  error. Authentication and list of customers working well.Having issues in Create New customers

**Comment by arulananth** [comment]
Issues on my local environment.
