### ISSUE TITLE
API MORE

### ISSUE THREAD

**Issue by arulananth** [mjaschen/collmex#154]
I want fetch follow the information

1.All Customers,
2.Products
3.Offers,
4.Orders.

There is any filter query ?

**Comment by mjaschen** [comment]
In the same order:

1. Just don't specify any fields (maybe besides `client_id`) in your `CUSTOMER_GET` query and you'll get all customer records in the response:

```php
<?php
$getCustomer = new CustomerGet([]);
$response = $request->send($getCustomer->getCsv());
```

The same applies for items 2. to 4.

**Comment by arulananth** [comment]
What about the contacts??
