### ISSUE TITLE
Collmex Anbindung an WooCommerce

### ISSUE THREAD

**Issue by Holger-Will** [mjaschen/collmex#16]
In der [Facebook User Group](https://www.facebook.com/groups/1334386849929218/) sucht jemand nach einer (rudimentären) Anbindung an WooCommerce. Da dies in PHP geschrieben ist dachte ich Du könntest vielleicht helfen...

**Comment by mjaschen** [comment]
Ich habe mir dafür selbst ein Skript gehackt, welches regelmäßig WooCommerce und Collmex miteinander abgleicht. Das ist aber nichts, was ich aktuell veröffentlichen kann.

**Comment by flowdee** [comment]
Ich kann verraten, dass ich bereits ein Collmex / WooCommerce Plugin in einer geschlossenen Beta laufen habe. Wenn du möchtest, kannst du gerne auf mich verweisen @Holger-Will ( https://flowdee.de/ )
