### ISSUE TITLE
Drop LeageCsvParser

### ISSUE THREAD

**Issue by oliverklee** [mjaschen/collmex#165]
Is `LeageCsvParser` still used, or can we drop it (together with the `LeageCsvGenerator`)? This would help simplify things a lot.

**Comment by mjaschen** [comment]
IMHO, we can drop it, as the default parser/generator work well.

(Originally it was created to test if was able to provide a workaround for [PHP bug #43225](https://bugs.php.net/bug.php?id=43225), but it unfortunately didn't.)
