### ISSUE TITLE
Hard-code the delimiter and enclosure for the CSV parsers

### ISSUE THREAD

**Issue by oliverklee** [mjaschen/collmex#166]
Can we hardcode (i.e., put them in constants) the delimiter and enclosure of the CSV parsers? As far as I can see, the code always uses the semicolon as delimiter and the double quote as enclosure. This would reduce code complexity.

**Comment by mjaschen** [comment]
Yes, that'd be not a problem as long as Collmex doesn't change the delimiter/enclosure character for the API responses. But that's unlikely anyway.
