### ISSUE TITLE
Split SimpleGenerator::generate

### ISSUE THREAD

**Issue by oliverklee** [mjaschen/collmex#177]
Currently, `SimpleGenerator::generate` can take an array of values (i.e., a single line) or an array of values (i.e., multiple lines). I propose we split this up into `generateFromSingleLine` and `generateFromMultipleLines` to have the typing more clear.

@mjaschen Would that be okay with you?

**Comment by oliverklee** [comment]
(And also, we can and should avoid overwriting the parameter variable `$data`.)

**Comment by Johnny99211** [comment]
I think this would make sense!

**Comment by mjaschen** [comment]
Implemented in 2.0.0.
