### ISSUE TITLE
Multiple Positions for Offers

### ISSUE THREAD

**Issue by arulananth** [mjaschen/collmex#178]
http://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,daten_importieren_nummernvergabe

any idea how call offers with multiple positions.

**Comment by oliverklee** [comment]
Hi @arulananth, does an approach like this work for you?
https://github.com/mjaschen/collmex/blob/master/docs/collmex.adoc#transmit-a-collmex-customer-order-with-multiple-items

**Comment by arulananth** [comment]
Thanks . Working well
