### ISSUE TITLE
Release 1.0.0 Changelog

### ISSUE THREAD

**Issue by Argee88** [mjaschen/collmex#192]
Hi,

I was going through the changelog of 1.0.0 and didn't find any explicitly described breaking changes. 
Can I still use the code as I did before or do I have to keep an eye on something special when updating?

**Comment by mjaschen** [comment]
Hi,

I'd check if the dependencies (PHP 7.1 + required libraries) are compatible with your environment. That's the major breaking change.

Further you should check for each item in the change log if it's relevant for your project (e.g. the changed method name `getJSON()` and the changed behaviour of `ZipResponse` handling).

**Comment by Argee88** [comment]
Okay, thank you :)
