### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by mjaschen** [mjaschen/collmex#194]
While running the tests with PHP 7.4 an error occurred:

```
There was 1 error:

1) MarcusJaschen\Collmex\Tests\Unit\Filter\Utf8ToWindows1252Test::filterStringKeepsAsciiTextUnchanged

Array and string offset access syntax with curly braces is deprecated
```

**Comment by mjaschen** [comment]
That's not an error in our library but in `neitanod/forceutf8`. I'll create a PR over there.

**Comment by sreimers** [comment]
Your open pull request seems to be superseded by this commit: https://github.com/neitanod/forceutf8/commit/4d1466ff0844b2421605a163048dbdd3a1f8b021

**Comment by mjaschen** [comment]
@sreimers Thanks for the update!

(What a small world this is – I'm a regular Studio Link user for podcast recording. Thanks for your work!)
