### ISSUE TITLE
Update minimum requirements as Tests with PHP 7.4 + Composer `--prefer-lowest` are failing

### ISSUE THREAD

**Issue by mjaschen** [mjaschen/collmex#198]

**Comment by mjaschen** [comment]
See https://travis-ci.org/mjaschen/collmex/jobs/643786982

**Comment by oliverklee** [comment]
This is a bug in older versions of Psalm. I propose we run the static analysis with PHP 7.3 only, and only the PHP linting and unit tests with all supported PHP versions. (In the https://github.com/MyIntervals/emogrifier project, we're current going this route.)

**Comment by mjaschen** [comment]
Issue no longer exists, closing it therefore.
