### ISSUE TITLE
Getting error during customer creation

### ISSUE THREAD

**Issue by Johnny99211** [mjaschen/collmex#203]
I'm getting this error when I want to create a new customer:

`Cannot determine MIME type for response`

This is the call I'm doing:

```
$default_customer_data = [
	'salutation'    => "Herr",
	'forename'      => "Charly",
	'lastname'      => "Cash",
	'street'        => "Hauptstraße 12",
	'zipcode'       => "12222",
	'city'          => "Berlin",
	'inactive'      => Customer::STATUS_ACTIVE,
	'country'       => "DE",
	'phone'         => "+49300000000",
	'email'         => "cash@example.org",
	'output_medium' => Customer::OUTPUT_MEDIUM_EMAIL,
];
$customer = new Customer( array_merge( $default_customer_data, $customer_data ) );
try {
	$this->collmex_request->send( $customer->getCsv() );
} catch ( RequestFailedException $e ) {
	error_log( print_r( $e, true ) );
} catch ( InvalidResponseMimeTypeException $e ) {
	error_log( print_r( $e, true ) );
}
```

As a result the customer get's not created in Collmex.

**Comment by Johnny99211** [comment]
By the way I'm using the latest version and I've also verified that the curl client get's setup correctly.

**Comment by mjaschen** [comment]
Can you please include the full exception contents? I'm particularly interested in the previous exception which is [catched here](https://github.com/mjaschen/collmex/blob/master/src/Response/ResponseFactory.php#L46).

My guess: the [Fileinfo extension](https://www.php.net/manual/en/book.fileinfo.php) is not installed for PHP.

**Comment by Johnny99211** [comment]
You were right. symfony/mime was missing. Can you add this as to you composer.json maybe?

**Comment by Johnny99211** [comment]
But now I'm getting a new error and I can't find any infos in the API docs from Collmex:

```
[parser:protected] => MarcusJaschen\Collmex\Csv\SimpleParser Object
    (
    )
[responseRaw:protected] => MESSAGE;E;205000;Firma 0 nicht vorhanden;2
[data:protected] => Array
    (
        [0] => Array
            (
                [0] => MESSAGE
                [1] => E
                [2] => 205000
                [3] => Firma 0 nicht vorhanden
                [4] => 2
            )
    )
[records:protected] => 
[isError:protected] => 
[errorCode:protected] => 
[errorMessage:protected] => 
[errorLine:protected] => 
```

**Comment by mjaschen** [comment]
> You were right. symfony/mime was missing. Can you add this as to you composer.json maybe?

Yes, of course. An issue was already opened :-)

**Comment by mjaschen** [comment]
> But now I'm getting a new error and I can't find any infos in the API docs from Collmex:

You have to provide the "[Firma Nr.](https://www.collmex.de/c.cmx?1005,1,help,daten_importieren_kunde)" in every record you are about to send to Collmex. The field is named `client_id` and it must contain the correct company number (probably `1`). The company number can be found in Collmex: "Verwaltung" > "Firma anzeigen und ändern".
