### ISSUE TITLE
Create an order with multiple items don't works like expected

### ISSUE THREAD

**Issue by Johnny99211** [mjaschen/collmex#209]
I need help. I've followed this page here to submit a new order with multiple items. Somehow in Collmex two different "Kundenaufträge" getting created for each order item:

https://github.com/mjaschen/collmex/blob/master/docs/collmex.adoc#transmit-a-collmex-customer-order-with-multiple-items

This is my implementation:

```
/**
 * @param array $order_data
 * @param null $order_items
 *
 * @return bool
 */
public function create_new_order( array $order_data, $order_items = null ): bool {
	$default_order_data = [
		'client_id' => $this->collmex_company_number
	];
	if ( ! empty( $order_items ) ) {
		$csv               = '';
		$merged_order_data = array_merge( $default_order_data, $order_data );
		foreach ( $order_items as $order_item ) {
			if ( ! empty( $order_item ) ) {
				$order = new CustomerOrder( array_merge( $merged_order_data, $order_item ) );
				$csv   .= $order->getCsv();
			}
		}
		try {
			$response = $this->collmex_request->send( $csv );
			error_log( print_r( $response, true ) );
			return true;
		} catch ( RequestFailedException $e ) {
			error_log( print_r( $e, true ) );
			return false;
		} catch ( InvalidResponseMimeTypeException $e ) {
			error_log( print_r( $e, true ) );
			return false;
		}
	}
	return false;
}
```

Instead cloning my array, I'm looping over the items array and do the same like in the docs - setting a new item:

![image](https://user-images.githubusercontent.com/43766368/93882994-38dbee00-fce1-11ea-9cf2-09525663126c.png)

**Comment by mjaschen** [comment]
There's an important bit missing in the documentation, it'll be fixed soon. Sorry for that.

Multiple line items belonging to the same Collmex record must be identified by the same numeric record ID (e.g. order ID oder invoice ID). 

The ID can be specified as a positive or a negative integer:

- Collmex will use the provided ID as record ID if a positive integer is provided
- Collmex will assign a new ID from the current auto-incrementing sequence if a negative integer is provided as ID

[The documentation describes that](https://www.collmex.de/c.cmx?1005,1,help,daten_importieren_nummernvergabe) in a detailed way.

In your example: create a random negative integer an set it as the `order_id` field for each line item before sending the request to Collmex.

**Comment by Johnny99211** [comment]
Alright I'll try that out and let you know if this works.
