### ISSUE TITLE
Datentyp LOGIN ist ungültig

### ISSUE THREAD

**Issue by flowdee** [mjaschen/collmex#21]
Bei Verwendung von LOGIN und Übergabe korrekter Zugangsdaten, bekommt man zusätzlich folgende Meldung zurück:

> Datentyp LOGIN ist ungültig. In der ersten Spalte muss der Datentyp stehen. Die gültigen Datentypen entnehmen Sie bitte der Hilfe

Mein Code schaut wie folgt aus:

```
// initialize HTTP client
$collmexClient = new CurlClient( $user, $password, $customer_id );

// create request object
$collmexRequest = new Request( $collmexClient );

// Creating test type
$login = new Login( array(
    'user' => $user,
    'password' => $password )
);

// send HTTP request and get response object
$collmexResponse = $collmexRequest->send( $login->getCsv() );
```

Die CSV die übertragen wird, scheint aber korrekt: `LOGIN;apiuser;apiuser`. Ist halt nur nervig, weil der Hinweis auch in Collmex selbst im API Log auftaucht.

Idee woran das liegen kann @mjaschen? Laut [Dokumentation](http://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,api_Authentifizierung) ist der Satztyp ja korrekt.

**Comment by mjaschen** [comment]
Leider keine Ahnung - ist mir noch nicht untergekommen :-(

**Comment by mjaschen** [comment]
`LOGIN` wird implizit bei jedem Request automatisch mitgesendet - evt. liegt es daran. Mit obigem Beispiel schickst du ja zweimal `LOGIN`, das zweite wird vom API-Endpoint angemeckert, weil es kein regulärer Typ ist.

**Comment by flowdee** [comment]
Achso verstehe. Mhhh dann prüfe ich die Zugangsdaten einfach mit ner normalen Abfrage von z.B. den Produkten. Oder hast du da ein anderes Best practice?

**Comment by Argee88** [comment]
Warum machst du überhaupt eine Login-Anfrage? :) Um die Login-Daten zu überprüfen?

**Comment by flowdee** [comment]
jop. Aber geht ja prinzipiell auch mit einer Produkt-Abfrage

**Comment by Argee88** [comment]
Genau das wollt ich anmerken ;)
