### ISSUE TITLE
Frage zu Rechnungenversendung

### ISSUE THREAD

**Issue by Johnny99211** [mjaschen/collmex#221]
Hallo Marcus,

besteht die Möglichkeit, in Collmex erstelle Rechnungen per API an den Kunden zu senden? Ich durchforste die API Docs nun schon eine Weile, kann jedoch keine entsprechende Option finden. Ist dir hier was bewusst?

Gruß
Jonathan

**Comment by mjaschen** [comment]
Hi,

das kenne ich nur im Zusammenhang mit dem Abrechnungslauf, hier kann man ein Flag setzen mit dem die Rechnung dann automatisch gemailt wird.

Ansonsten einfach die Rechnung als PDF abrufen und dieses selbst schnell in eine Mail packen (so mache ich es für diverse Kunden).

**Comment by Johnny99211** [comment]
Hi Marcus,

Collmex war so nett und hat mir einen solchen Endpunkt zur Verfügung gestellt. PR ist gestellt.


Gruß
Jonathan

**Comment by Johnny99211** [comment]
Hi Marcus,

irgendwie scheint der PR wieder Probleme mit der Formatierung zu haben. Ich kann gerne neu formatieren, wenn du mir deine Formatting Rules schicken würdest. Das würde sehr helfen! Dann kannst du schnell mergen und ich die neue Satzart in Composer durch die neue Version abrufen.

Gruß
Jonathan

**Comment by mjaschen** [comment]
Bin gerade unterwegs, melde mich nachher.

**Comment by mjaschen** [comment]
Du kannst den Coding Style mit `composer fix:php-cs` einmal global fixen. 

In [`.php_cs.dist`](https://github.com/mjaschen/collmex/blob/main/.php_cs.dist) kannst du die aktuelle Konfiguration sehen.
