### ISSUE TITLE
Error 500 Fehler bei MultiRequest in Verbindung mit "order_id"

### ISSUE THREAD

**Issue by Lord-EXE** [mjaschen/collmex#223]
Hallo Herr Marcus Jaschen,

ich muss mehrere Artikel in einer Bestellung an Collmex übergeben.
Leider kam es dabei zu dem Problem das für jeden Artikel ein seperater Auftrag angelegt wurde.
Nach kurzer Rücksprache mit Collmex stellte sich dann heraus, dass dies an der fehlenden "order_id" liegt.
Wenn ich nun eine "order_id" angebe in dem von ihnen genannten Beispiel kommt es zu folgendem Fehler.

```
$customerOrderData = [
    ...
    'order_id' => '-1000',
    'customer_salutation' => 'Herr',
    ...
];
```

```
Notice: Undefined variable: collmexClient in /home/users/xxxx/www/play_place/collmex/collmex.php on line 76

Fatal error: Uncaught TypeError: Argument 1 passed to MarcusJaschen\Collmex\AbstractRequest::__construct() must be an instance of MarcusJaschen\Collmex\Client\ClientInterface, null given, called in /home/users/xxxx/www/play_place/collmex/collmex.php on line 76 and defined in /home/users/xxxx/www/play_place/collmex/mjaschen/collmex/src/AbstractRequest.php:31 Stack trace: #0 /home/users/xxxx/www/play_place/collmex/collmex.php(76): MarcusJaschen\Collmex\AbstractRequest->__construct(NULL) #1 /home/users/xxxx/www/play_place/index.php(3): include('/home/users/web...') #2 {main} thrown in /home/users/xxxx/www/play_place/collmex/mjaschen/collmex/src/AbstractRequest.php on line 31
```

Mache ich einen Fehler oder liegt hier ein anderes Problem vor? Vielen Dank bereits im Vorfeld für ihre Hilfe.

Mit freundlichen Grüßen Sebastian Pöllath

**Comment by mjaschen** [comment]
Hallo,

die `Request`-Instanz wird nicht mit einer `Client`-Instanz als Konstruktor-Argument aufgerufen (`collmex.php`, Zeile 76). Sobald das behoben wird, verschwindet der Fehler.

In etwa so:

```php
$collmexClient = new \MarcusJaschen\Collmex\Client\Curl('USER', 'PASSWORD', 'CUSTOMER_ID');
$collmexRequest = new \MarcusJaschen\Collmex\Request($collmexClient);
```

**Comment by Lord-EXE** [comment]
Das war dann wohl mein Fehler. Vielen Dank für die schnelle Hilfe
