### ISSUE TITLE
How can I get the CSV file from a response?

### ISSUE THREAD

**Issue by Johnny99211** [mjaschen/collmex#226]
Hi,

I want to know how I can get the returned CSV file from Collmex when using SALES_ORDER_GET? I need to save the CSV file on an FTP storage so I somehow need this file. I know that I can create a CSV myself but the Collmex docs are saying that there is a CSV file returned. Any documentation in combination with your PHP API?

Thanks a lot!
Johnny

**Comment by mjaschen** [comment]
You can get the raw response content (which is the CSV data for a `CsvResponse`) with [CsvResponse::getResponseRaw()](https://github.com/mjaschen/collmex/blob/4960db8afe44dda9207b181459bec1b9e4ddd4bc/src/Response/CsvResponse.php#L155):

```php
[...]
$response = $request->send($requestData);

$csv = $response->getResponseRaw();

file_put_contents('response.csv', $csv);
```

**Comment by Johnny99211** [comment]
Thanks! Unfortunately it looks like that the CSV headers are missing in the raw response? Or am I wrong?

**Comment by mjaschen** [comment]
Collmex doesn't send any header rows. That's due to the fact that a response contains different record types, so headers wouldn't make sense at all.

**Comment by Johnny99211** [comment]
Ok so I will add my own headers! Thanks so far!
