### ISSUE TITLE
Total amount of products?

### ISSUE THREAD

**Issue by Johnny99211** [mjaschen/collmex#230]
Hi Marcus,

do you know if there is a limit of products that can be imported from Collmex? A customer of me tried importing 700+ products and ran into a timeout.

BG
John

**Comment by mjaschen** [comment]
Hi John,

I don't know if there's a limit. I think Collmex support can answer this question (https://www.collmex.de/kontakt.html)

**Comment by Johnny99211** [comment]
Hi Marcus,

the only thing I know is that Collmex previously added an API limit of 10k calls, which I think was a bad idea if you look at my customer with 700+ products.... But I'll try contacting Collmex again. Good to know that there is no limit / timeout if your PHP lib.

**Comment by mjaschen** [comment]
We use the default timeout settings for PHP's curl extension. Most timeout values are set to `0` which means there's no timeout enforced.

But it's possible that the PHP ini setting for `max_execution_time` is reached and your program is terminated. Maybe increasing `max_execution_time` can help in your case.
