### ISSUE TITLE
Missleading information regarding numeric money values in README.md?

### ISSUE THREAD

**Issue by kirladu** [mjaschen/collmex#236]
Hi,

first things first: thanks a lot for this project and the great work!

Implementing an order sync to Collmex I ran into an issue setting prices in the order positions (or other fields).

In the README.md float values get inserted into the arrays directly:

```php
$customerOrderItem = new CustomerOrder(
    array_merge(
        $customerOrderData,
        [
            ...
            'price' => 37.99,
            ...
        ]
    )
);
```

When I call the API with this request Collmex will save the value "3799,00" in the order position.
Everything's fine as soon as I convert the value to "37,99" (as string) beforehand.

I checked the source code, but could not find a conversion from float to string which would do the job.

Did I miss anything?

If not: certainly converting the price numbers to the correct string format should be no problem for any developer, but we should fix the documentation then. I can prepare a PR if helpful.

**Comment by mjaschen** [comment]
Hi,

thanks for reporting this.

We don't convert numeric values – they're expected in the format `NNNN,NN` (comma as decimal separator) as described in the [API documentation](https://www.collmex.de/c.cmx?1005,1,help,daten_importieren_datentypen_felder).

It'd be nice if you can add a clarifying paragraph to `README.md` and open a PR. Thanks :-)
