### ISSUE TITLE
Parser not working correctly

### ISSUE THREAD

**Issue by Johnny99211** [mjaschen/collmex#238]
Hi Marcus,

I've figured out an issue with the parser. I have a customer which uses the old Collmex webshop. He pasted a lot of HTML text into the "Lang-Text" field. In case the text has some line breaks or white spaces between the HTML elements, the parser has a lot of problems and recognizes some part of text as a new dataset:

![image](https://user-images.githubusercontent.com/43766368/156159753-facf83fb-7dd8-4cb4-ace7-17b3986ef0c4.png)

Also, an error gets thrown since the text is logically not within the records type map:

`"Invalid\/Unsupported Record Type Identifier:`

Its currently not possible for the customer to import the products.

**Comment by mjaschen** [comment]
Can you create a test case in `tests/`?

**Comment by Johnny99211** [comment]
Within which file? I only have the response data from the request received from Collmex:

`CMXPRD;143;LASER ProDuro DR BIG SR41-42;LASER ProDuro exhausts DR BIG SR41-42;PCE;14 Abgasanlage;1 HESSLER RALLYE TEAM;0 19%;5,500;KGM;1;0 Ware;0;0 Standard;409,00;;LASER;3 Standardversand;0;1;;0 Einkauf;;;;;0 Automatisch;0,00;1;;;;;;;;;;;;1 www.DR-BIG-SHOP.de;LASER ProDuro DR BIG SR41-42;"<p>(English description below)</p>
<p>Die Edelstahl - Schalld&auml;mpfer - L&ouml;sung f&uuml;r die DR BIG!</p>
<p>\Rallye tested\"" :-)</p><p><strong><u>Tipp:</u></strong><br /> Der Laser ist bei uns noch im Programm, weil er unbestritten schick aussieht.&nbsp;<br /> Unser neuer <a href=""http://www.dr-big-shop.de/BIG_Auspuff_875.html"">Sebring HRT </a>- ebenfalls komplett aus Edelstahl hergestellt sieht aber auch nicht schlecht aus - und kann mehr Leistung bieten... naa?</p><p>Und lies die TechnikTipps!<br /> <u><a href=""http://drbigtechnikhrt.blogspot.de/2014/12/auspuff-tuning-dr-big.html"">http://drbigtechnikhrt.blogspot.de/2014/12/auspuff-tuning-dr-big.html</a></u></p><p><strong><u>Zulassung:</u></strong><br /> E-gepr&uuml;ft</p><p>&nbsp;</p><h3><strong><u>LASER ProDuro DR BIG SR41-42</u></strong></h3>
<p><strong>Available on demand</strong></p><p>The stainless steel - muffler - solution for the DR BIG!</p><p>\ Rallye tested \ "":-)</p><p><strong><u>Tip:</u></strong><br /> We have the Laser ProDuro muffler still in the range because it looks very good.<br /> But our new <a href=""http://www.dr-big-shop.de/BIG_Auspuff_875.html"">Sebring HRT </a>- also made of stainless steel, does not look bad also - and offers more power &#128521;</p><p>And please have a look at the technic tips!<br /><a href=""http://drbigtechnikhrt.blogspot.de/2014/12/auspuff-tuning-dr-big.html"">http://drbigtechnikhrt.blogspot.de/2014/12/auspuff-tuning-dr-big.html</a><br /> [<em>sorry, the blog is not yet translated to English but Google translator should be an option</em>]</p>
<p><strong><u>Approval:</u></strong><br /> E-approved</p>";1;143.html;;;0;https://lh6.googleusercontent.com/-udc-UlTcHG4/VFp68bEF02I/AAAAAAAAFcA/rPZm02lSZKQ/w628-h420-no/02_AuspuffLaserProDuro.jpg;0,000;0,000;0;1;0;12;;;;;0;;;0;;;0
CMXPRD;144;LASER ProDuro DR BIG SR43 / mit D�senkit;LASER ProDuro exhaust DR BIG SR43/ include jetkit;PCE;14 Abgasanlage;1 HESSLER RALLYE TEAM;0 19%;5,500;KGM;1;0 Ware;0;0 Standard;429,00;;LASER;3 Standardversand;0;1;;0 Einkauf;;;;;0 Automatisch;0,00;1;;;;;;;;;;;;1 www.DR-BIG-SHOP.de;LASER ProDuro DR BIG SR43 / mit D�senkit;"<p>(English description below)</p>
<p>Die Edelstahl - Schalld&auml;mpfer - L&ouml;sung f&uuml;r die DR BIG!</p>
<p>\Rallye tested\"" :-)</p>
<p>F&uuml;r die DR BIG SR43 liefern wir den LASER mit dem unbedingt n&ouml;tigen und passenden D&uuml;senkit!<br /> <br /> <strong><u>Tipp:</u></strong><br /> Der Laser ist bei uns noch im Programm, weil er unbestritten schick aussieht.&nbsp;<br /> Unser neuer <a href=""http://www.dr-big-shop.de/BIG_Auspuff_875.html"">Sebring HRT </a>- ebenfalls komplett aus Edelstahl hergestellt sieht aber auch nicht schlecht aus - und kann mehr Leistung bieten... naa?</p>
<p>Und lies die TechnikTipps!<br /> <u><a href=""http://drbigtechnikhrt.blogspot.de/2014/12/auspuff-tuning-dr-big.html"">http://drbigtechnikhrt.blogspot.de/2014/12/auspuff-tuning-dr-big.html</a></u></p>
<p><strong><u>Zulassung:</u></strong><br /> E-gepr&uuml;ft</p>
<p>&nbsp;</p>
<h3><strong><u>LASER ProDuro DR BIG SR43 &ndash; INCL. JET KIT</u></strong></h3>
<p><strong>Available on demand</strong></p>
<p>The stainless steel - muffler - solution for the DR BIG!</p>
<p>\ Rallye tested \ "":-)</p>
<p>For the DR BIG SR43 we deliver the Laser ProDuro including the needed jet kit.</p>
<p><strong><u>Tip:</u></strong><br /> We have the Laser ProDuro muffler still in the range because it looks very good.<br /> But our new <a href=""http://www.dr-big-shop.de/BIG_Auspuff_875.html"">Sebring HRT </a>- also made of stainless steel, does not look bad also - and offers more power &#128521;</p>
<p>And please have a look at the technic tips!<br /> <a href=""http://drbigtechnikhrt.blogspot.de/2014/12/auspuff-tuning-dr-big.html"">http://drbigtechnikhrt.blogspot.de/2014/12/auspuff-tuning-dr-big.html</a><br /> [<em>sorry, the blog is not yet translated to English but Google translator should be an option</em>]</p>
<p><strong><u>Approval:</u></strong><br /> E-approved</p>`

**Comment by Johnny99211** [comment]
I've checked it again. The issue seems to be the delimiter which is used within the text field by the customer. I think its not a bug.

**Comment by Johnny99211** [comment]
Seems like I‘ve closed it too early:

„ Semikolons können in jedem Textfeld vorkommen. Damit muss ihre Software 
umgehen können.

s. Regel 4:

https://www.collmex.de/c.cmx?1005,1,help,daten_importieren_csv

Beginnt ein Feld mit einem "-Zeichen, müssen Sie die Daten so lange 1:1 
einlesen, bis das abschließende "-Zeichen kommt. Einzige Ausnahme: 
Doppelte "-Zeichen sind durch ein einzelnes "-Zeichen zu ersetzten (s. 
Regel 5).

Zur Lösung des Problems müssen Sie Ihre Software entsprechend anpassen.

--
Mit freundlichen Grüßen aus Saarbrücken ...
Bastian Wetzel“

**Comment by Johnny99211** [comment]
Talked again to Mr. Wetzel. Since " is the enclosure and ; the divider, there is no way for us to check if its a new field or just some content I think. What do you think?

**Comment by mjaschen** [comment]
Ok, I'd like to take a closer look, but I need a complete and unchanged CSV record for this. Can you create a gist at <https://gist.github.com>?

**Comment by Johnny99211** [comment]
Sure! Mr. Wetzel told me to end the coworking with you and other people and will block all the testaccounts in case we don't fix this. Actually, I think this is unfair since the customer needs to follow the rules for texts within free text fields. I see no chance here, since when we get some text via the API, the enclosure " can be closed by the customer within the field in case he adds some HTML....

**Comment by Johnny99211** [comment]
Here (please remove comment with link after you have received the gist file)!

https://gist.github.com/Johnny99211/56794189f3b7c94c3466825432ecc6f0

**Comment by mjaschen** [comment]
Bugfix published in 2.1.1. Can you confirm?

**Comment by Johnny99211** [comment]
Thanks for the fast solution. Doing some tests now. Inform you asap.

**Comment by Johnny99211** [comment]
Seems like its working! Still testing but first poi looking good

**Comment by Johnny99211** [comment]
Did some extended testing now! Awesome, seems to work now :) Thanks a lot!
