### ISSUE TITLE
STOCK_CHANGE_GET missing fields

### ISSUE THREAD

**Issue by shahtaj-qasim** [mjaschen/collmex#241]
Some fields in STOCK_CHANGE_GET request (Field 11, 12, 13, 14 ) are not present in the API PHP SDK. Could you please add them?

![image](https://user-images.githubusercontent.com/61311949/156572665-013274f1-d70c-4dbe-afea-41abb1f791c3.png)

**Comment by mjaschen** [comment]
Fixed in version 2.2.0.
