### ISSUE TITLE
UTF-8 issue

### ISSUE THREAD

**Issue by Johnny99211** [mjaschen/collmex#243]
Hi!

Every time I request something with the new 2.1.1 version, I'm getting this error message within the response:

`Invalid UTF-8 String.`

Any idea why this happens? Collmex responded that there are no issues within the logs there.

**Comment by mjaschen** [comment]
I've no idea where that come from. The whole project including its dependencies does not contain that string (`grep -r 'Invalid UTF-8 String' .`)

Can you use step-debugging or something similar to isolate the cause?

**Comment by Johnny99211** [comment]
Hi!

I did something wrong during coding. I've used `substr` for shortening a string passed as system name to Collmex. This customer entered a system name with an Ü. Because of substr, the Ü was converted to a non-UTF-8 string which then caused an issues at Collmex. My fault. Fixed it by using `mb_substr` now.
