### ISSUE TITLE
Update für Laravel 5.4/5.5 ?

### ISSUE THREAD

**Issue by Naoray** [mjaschen/collmex#25]
Gibt es irgendwelche Pläne das Package für die Nutzung in Laravel 5.4/5.5 zu updaten?

**Comment by mjaschen** [comment]
Hallo,

ja, es gibt bereits ein Ticket dafür (#13). Vielleicht schaffe ich es jetzt zum Jahresende noch!

Viele Grüße

Marcus

**Comment by mjaschen** [comment]
Wenn du Lust und Zeit hast, kannst du natürlich auch einen PR machen ;-)

**Comment by Naoray** [comment]
@mjaschen wofür wird https://github.com/mjaschen/collmex/blob/master/config/config.php#L8 genutzt?

**Comment by mjaschen** [comment]
Das ist das Config-File-Template für den Laravel 4 Service Provider.

**Comment by Naoray** [comment]
ja, das ist mir klar, aber ich finde im code nirgendswo `config('collmex.client_id')`. Wird dieses eine Zeile also noch verwendet und wenn ja wo?

**Comment by mjaschen** [comment]
Ja, es wird verwendet - [in `CollmexServiceProvider`](https://github.com/mjaschen/collmex/blob/aee568ffe90cfba6e03a5b24a4b6fbe3f1c15dd2/src/CollmexServiceProvider.php#L53-L55).

Laravel 4 lädt Config-Files automatisch und erstellt implizit einen Config-Namespace. Die Werte kann man sich dann mit dem Container wieder unter Angabe des Config-Namespaces (`collmex.`) herausfischen.

**Comment by Naoray** [comment]
@mjaschen da sehe ich aber nur die 3 anderen Werte aus der config => https://github.com/mjaschen/collmex/blob/master/config/config.php#L9-L11

aber es fehlt die nutzung von `client_id`, oder?

**Comment by mjaschen** [comment]
`client_id` wird/wurde tatsächlich nicht benutzt, da hast du recht.

**Comment by Naoray** [comment]
Gut, dann habe ich die config in #26 mal rausgenommen.

**Comment by Naoray** [comment]
@mjaschen schaust du dir den PR #26 mal an und merged den wenn du zufrieden bist?

**Comment by Naoray** [comment]
wäre super wenn du das heute mergen könntest:)

**Comment by mjaschen** [comment]
Erledigt, danke!
