### ISSUE TITLE
CMXVAG - Satzart Lieferantenvereinbarungen

### ISSUE THREAD

**Issue by yii-spot** [mjaschen/collmex#258]
Hello all,

has anyone already planned to extend the API library for the new type CMXVAG (vendor agreements)?

https://www.collmex.de/c.cmx?1005,1,help,daten_importieren_lieferantenvereinbarungen

If not, I will prepare a PR, because we need in a project the possibility to import supplier prices automatically into Collmex.

**Comment by mjaschen** [comment]
Feel free to create a PR! 👍

**Comment by mjaschen** [comment]
Just tagged 2.5.1 which contains `CMXVAG` (class is named `SupplierAgreement` to match other supplier-related types).

**Comment by yii-spot** [comment]
@mjaschen Thank you! 👍
