### ISSUE TITLE
Satzarten

### ISSUE THREAD

**Issue by Holger-Will** [mjaschen/collmex#3]
"There is (or least should be…) a Type class for every Collmex record type ("Satzart"). Currently only the base types (MESSAGE, LOGIN, NEW_OBJECT_ID) and a few normal record types (CMXKND, CMXINV, CMXABO, CMXUMS) are implemented."

ich bin gerade dabei etwas ähnliches wie Ihr Projekt für node.js zu schreiben. Vielleicht ist folgende Datei auch für Ihr Projekt hilfreich:

https://github.com/klimapartner/co-collmex/blob/master/modules/satzarten.json

**Comment by mjaschen** [comment]
Hallo,

danke, ich schau’s mir mal an!

Viele Grüße

Marcus


On 6 Nov 2016, at 19:29, Holger Will wrote:

> "There is (or least should be…) a Type class for every Collmex record type ("Satzart"). Currently only the base types (MESSAGE, LOGIN, NEW_OBJECT_ID) and a few normal record types (CMXKND, CMXINV, CMXABO, CMXUMS) are implemented."
>
> ich bin gerade dabei etwas ähnliches wie Ihr Projekt für node.js zu schreiben. Vielleicht ist folgende Datei auch für Ihr Projekt hilfreich:
>
> https://github.com/klimapartner/co-collmex/blob/master/modules/satzarten.json
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mjaschen/collmex/issues/3




-- 
Marcus Jaschen
Bahnhofstr. 10
12555 Berlin
Germany

+4915123038682
mail@marcusjaschen.de
GPG Key: https://marcusjaschen.de/_assets/0xCE13FDF2.asc
https://www.marcusjaschen.de/
