### ISSUE TITLE
Disable merge commits for PRs

### ISSUE THREAD

**Issue by oliverklee** [mjaschen/collmex#40]
I propose disabling this checkbox in the GitHub repository settings:

Settings > Options > Merge button > Allow merge commits 

This will make sure that a merged PR will only create one commit in the history, not two (the actual change and the merge commit), helping to keep the git history clean and readable.

**Comment by mjaschen** [comment]
That's a good idea, thanks! Setting is changed now.

**Comment by oliverklee** [comment]
I think this still has not changed - there still are merge commits for merged PRs.
