### ISSUE TITLE
Remove file DocBlocks

### ISSUE THREAD

**Issue by oliverklee** [mjaschen/collmex#44]
AFAICS, the file DocBlocks of this project contain only information that also is part of the class DocBlocks. So I propose to remove the file DocBlocks to remove these redundancies and keep the files smaller. @mjaschen What do you think?

**Comment by oliverklee** [comment]
@mjaschen Any thoughts?

**Comment by mjaschen** [comment]
Hi Oliver,

file level doc blocks can be removed, as they don't provide any benefits nowadays :-)
