### ISSUE TITLE
CustomerOrder: Mehrere Produkte zu einem Auftrag

### ISSUE THREAD

**Issue by blueeyez22** [mjaschen/collmex#61]
Hi,

ist es möglich beim Anlegen eines Kundenauftrags (CustomerOrder) mehrere Produktnummern anzugeben? Im Moment scheint das Feld "product_id" das nicht zu erlauben. An sich würde die Collmex API das unterstützen.

Aus der [Collmex API Doku](http://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,daten_importieren_kundenauftraege):

> Jede Kundenauftrags-Position ist eine Zeile in der CSV-Datei. Alle Positionen eines Auftrags müssen in aufeinander folgenden Zeilen stehen. Die Kopfdaten (z.B. Kunde, Zahlungsbedingung, Versandart usw.) müssen für alle Positionen / Zeilen angegeben werden.

**Comment by mjaschen** [comment]
Hallo,

aktuell gibt es das Konzept einer Collection von Datensätzen noch nicht (kommt aber irgendwann).

Du kannst bis dahin einfach mehrere CustomerOrder-Instanzen erstellen und diese dann vor dem Senden aneinander hängen:

```php
<?php

use MarcusJaschen\Collmex\Client\Curl as CurlClient;
use MarcusJaschen\Collmex\Request;
use MarcusJaschen\Collmex\Type\Customer;

// initialize HTTP client
$collmexClient = new CurlClient('USER', 'PASSWORD', 'CUSTOMER_ID');

// create request object
$collmexRequest = new Request($collmexClient);

$customerOrderItem1 = new CustomerOrder(
    [
        'client_id'                      => '2',
        'order_id'                       => null,
        'position'                       => null,
        'order_type'                     => null,
        ...
        'product_id' => '12345',
        ...           
    ]
);

$customerOrderItem2 = clone $customerOrderItem1;
$customerOrderItem2->product_id = '23456';

$csv = $customerOrderItem1 . PHP_EOL . $customerOrderItem2;

// send HTTP request and get response object
$collmexResponse = $collmexRequest->send($csv);

if ($collmexResponse->isError()) {
    echo 'Collmex error: ' . $collmexResponse->getErrorMessage() . '; Code=' . $collmexResponse->getErrorCode() . PHP_EOL;
} else {
    $newObject = $collmexResponse->getFirstRecord();
    echo 'New Collmex customer ID=' . $newObject->new_id . PHP_EOL;

    $records = $collmexResponse->getRecords();

    foreach ($records as $record) {
        // contains one NewObject object and the Message object(s)
        var_dump($record->getData());
    }
}
```

**Comment by blueeyez22** [comment]
Hi,

super Tipp. In deinem Beispielcode hat sich aber noch ein Fehler eingeschlichen:

In folgender Zeile fehlt jeweils ein `->getCsv()`.

`$csv = $customerOrderItem1 . PHP_EOL . $customerOrderItem2;`

Vllt kannst du das in deiner vorherigen Antwort bearbeiten, falls jemand mal diesen Thread finden sollte.

Danke nochmal für die schnelle Hilfe.

**Comment by mjaschen** [comment]
Danke, du hast recht. Ich ändere es.

**Comment by oliverklee** [comment]
@mjaschen Zwischen den Zeilen in einer CSV-Datei muss laut https://tools.ietf.org/html/rfc4180 immer CRLF stehen, nicht PHP_EOL (was je nach Betriebssystem unterschiedlich ist). Könntest du den Beispielcode oben bitte entsprechend anpassen? Vielen Dank!

**Comment by oliverklee** [comment]
… wobei ich gerade gesehen habe, dass `->getCsv()` immer ein LF anhängt. Daher bräuchte man gar keinen (zusätzlichen) Glue zwischen den CSV-Zeilen mehr.
