### ISSUE TITLE
Issues with the samples

### ISSUE THREAD

**Issue by strausmann** [mjaschen/collmex#64]
Hello,

i have problems with the samples in the readme.

The getCustomer nothing return. The RAW Data has content. But the Array is empty. I see in the RAW Output Charset problems.

The same problem with the new Customer() Request. The Customer is succesful created but the new Customer ID is not return.

Debugging the $collmexResponse Content has the same charset issue.

![image](https://user-images.githubusercontent.com/4519228/37402106-9e6caaf4-278a-11e8-98b4-c2f9108c30ef.png)

How can i fix that?

Thanks
Regards,
Bjoern

**Comment by mjaschen** [comment]
The response seems to be ok.

The message says that a new record with the ID = 10005 was created at Collmex. You have to sent another request (`CUSTOMER_GET`) to the API to get the actual customer data:

```php
$collmexClient = new CurlClient('USER', 'PASSWORD', 'CUSTOMER_ID');
$collmexRequest = new Request($collmexClient);
$getCustomerType = new CustomerGet(array('customer_id' => '10005'));
$collmexResponse = $collmexRequest->send($getCustomerType->getCsv());

var_dump($collmexResponse);
```

**Comment by strausmann** [comment]
Yes, the CSV contain the customer ID but getFirstRecord() retrurn nothing. This is my Problem.

**Comment by strausmann** [comment]
And her is my Test 

![image](https://user-images.githubusercontent.com/4519228/37402811-29516be4-278d-11e8-8083-57d7de2bd853.png)

This Return the following:

![image](https://user-images.githubusercontent.com/4519228/37402833-38f3685e-278d-11e8-992d-00036a3b1ccd.png)

**Comment by mjaschen** [comment]
Can you show us the output of `var_dump($collmexResponse->getRecords())`?

**Comment by strausmann** [comment]
Its "NULL"

**Comment by mjaschen** [comment]
Ok, that's very strange. I tried it with an OCR-version of your response (maybe you can provide us raw textual data instead of screenshots next time) and it worked flawlessly:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$data = 'CMXKND;10005;1 Strausmann Services — DEV;Herr;;Charly;Cash;Test Firma;;Hauptstraße 12;12222;Berlin;;0;DE;+49300000000;;cash@example.org;;;;;;;;0 30 Tage ohne Abzug;0;;;1 E-Mail;;;;0 Standard;EUR;0;;;0;0;;0 Deutsch;;;;;0;0;0;;0;0'
    . PHP_EOL
    . 'MESSAGE;S;208013;CUSTOMER GET hat 1 Datensätze zurückgegeben'
    . PHP_EOL
    . 'MESSAGE;S;204020;Datenübertragung erfolgreich. Es wurden 1 Datensätze verarbeitet.';
$parser = new \MarcusJaschen\Collmex\Csv\SimpleParser();
$responseFactory = new \MarcusJaschen\Collmex\Response\ResponseFactory($data, $parser);

var_dump($responseFactory->getResponseInstance());

```

It's possible that there's something wrong with your PHP installation as the `$data` attribute of your `CsvReponse` is empty which definitively shouldn't be the case.

Is it possible for you to use a debugger and look step for step what's happening in `CsvResponse::__construct()`, especially in the `parseCsv()` call ([line 89][parsecsv])?

[parsecsv]: https://github.com/mjaschen/collmex/blob/master/src/Response/CsvResponse.php#L89

**Comment by strausmann** [comment]
Hi, i use a Ubuntu 16.04 Server managed with RunCloud. On my Plesk 17.5 Server with CloudLinux its works. Help you my PHPInfo ?

I tried your test again with me. Here again nothing is spent. Are any PHP extensions needed?

**Comment by strausmann** [comment]
I tested something. The variable $responseBody contains the CSV content. For me, the function parse($csv) seems to be the problem. 

https://github.com/mjaschen/collmex/blob/master/src/Response/CsvResponse.php#L102

**Comment by mjaschen** [comment]
Yeah, as I supposed. Can you take a look with a debugger why it returns an empty value?

**Comment by strausmann** [comment]
I have no xdebug available. How can I get the desired data?

**Comment by mjaschen** [comment]
I think you've to add `var_dump()` statements in every function call inside `parseCsv()` and try to find out where the data is disappearing. Unfortunately it's impossible to tell what's going wrong from here.

**Comment by strausmann** [comment]
Her the Output:

```
/home/whmcsdev02/webapps/whmcsdev02/public/collmex/vendor/mjaschen/collmex/src/Response/CsvResponse.php:101:string 'CMXKND;10005;1 Strausmann Services — DEV;Herr;;Charly;Cash;Test Firma;;Hauptstraße 12;12222;Berlin;;0;DE;+49300000000;;cash@example.org;;;;;;;;0 30 Tage ohne Abzug;0;;;1 E-Mail;;;;0 Standard;EUR;0;;;0;0;;0 Deutsch;;;;;0;0;0;;0;0
MESSAGE;S;208013;CUSTOMER GET hat 1 Datensätze zurückgegeben
MESSAGE;S;204020;Datenübertragung erfolgreich. Es wurden 1 Datensätze verarbeitet.' (length=379)
/home/whmcsdev02/webapps/whmcsdev02/public/collmex/vendor/mjaschen/collmex/src/Response/CsvResponse.php:103:
array (size=0)
  empty
/home/whmcsdev02/webapps/whmcsdev02/public/collmex/vendor/mjaschen/collmex/src/Response/CsvResponse.php:245:
array (size=0)
  empty
/home/whmcsdev02/webapps/whmcsdev02/public/collmex/test.php:14:
object(MarcusJaschen\Collmex\Response\CsvResponse)[4]
  protected 'parser' => 
    object(MarcusJaschen\Collmex\Csv\SimpleParser)[3]
      protected 'delimiter' => string ';' (length=1)
      protected 'enclosure' => string '"' (length=1)
  protected 'responseRaw' => string 'CMXKND;10005;1 Strausmann Services — DEV;Herr;;Charly;Cash;Test Firma;;Hauptstraße 12;12222;Berlin;;0;DE;+49300000000;;cash@example.org;;;;;;;;0 30 Tage ohne Abzug;0;;;1 E-Mail;;;;0 Standard;EUR;0;;;0;0;;0 Deutsch;;;;;0;0;0;;0;0
MESSAGE;S;208013;CUSTOMER GET hat 1 Datensätze zurückgegeben
MESSAGE;S;204020;Datenübertragung erfolgreich. Es wurden 1 Datensätze verarbeitet.' (length=379)
  protected 'response' => null
  protected 'data' => 
    array (size=0)
      empty
  protected 'records' => null
  protected 'isError' => null
  protected 'errorCode' => null
  protected 'errorMessage' => null
  protected 'errorLine' => null
```
I can offer access to a Cloud IDE to take a closer look at the problem.

**Comment by mjaschen** [comment]
Hi!

I've added an alternative way to parse the CSV data using the [CSV library](http://csv.thephpleague.com/) from *The PHP League*.

Maybe you can give it a try?

To use the alternative parser you've to do the following steps:

- install CSV library from The PHP League: `composer require league/csv:^8.0`
- use the alternative parser instead of the included one: replace the `$parser` instantiation described in [this example](https://github.com/mjaschen/collmex/issues/64#issuecomment-373018598) with `$parser = new \MarcusJaschen\Collmex\Csv\LeagueCsvParser();`

**Comment by strausmann** [comment]
Perfect, this looks like better for me, its working now.
Thank you

**Comment by mjaschen** [comment]
That's great to hear!

**Comment by lenusch** [comment]
Hello? We need this too. :-)

**Comment by mjaschen** [comment]
Hi,

I'll do a release containing this change on monday.

**Comment by strausmann** [comment]
Thank you

**Comment by mjaschen** [comment]
It's possible to use a custom CSV parser for API responses. The README was extended with an example on how to do this: 

<https://github.com/mjaschen/collmex#use-a-different-csv-parser-for-the-response-data>

Let me know if it works.

**Comment by strausmann** [comment]
Hello,

i got a exception become...

![image](https://user-images.githubusercontent.com/4519228/44980264-a89ea500-af6f-11e8-9026-cb4c7ec5445f.png)

Regards,

Bjoern

**Comment by mjaschen** [comment]
Which version of the League CSV library do you use?

**Comment by strausmann** [comment]
I use 9.1.4

**Comment by mjaschen** [comment]
Please use 8.x for now.

I'll add a 9.x compatible parser in the next days.

**Comment by strausmann** [comment]
Ok, thank you. Thats working now...

**Comment by mjaschen** [comment]
The CSV parser should work now with League CSV versions 8.x as well as with 9.x.
