### ISSUE TITLE
Mehrere query-Parameter pro Anfrage an Api

### ISSUE THREAD

**Issue by Argee88** [mjaschen/collmex#69]
Ich habe das Gefühl, dass Fragen hier gerne auf Deutsch behandelt werden, deshalb auf Deutsch:

Weiß jemand, ob es die CollmexAPI unterstützt in einer Datenabfrage mehrere Query-Zeilen zu senden? Zum Beispiel, wenn ich drei Produkte nach ProduktId abfragen möchte, mache ich im Moment für jedes Produkt eine eigene Abfrage. Viel lieber wäre es mir, wenn ich das mit einer einzelnen Abfrage könnte. In einer SDK Implementierung würde ich dann das entsprechende Feld als Array übergeben wollen:
```php
$getProductType = new ProductGet([
    'client_id' => '1',
    'product_id' => ['1', '2', '3']
]);
```
Wenn die API das nicht unterstützt, danke ich für die Auskunft und vergesst das wünschenswerte Feature wieder ;)

**Comment by mjaschen** [comment]
Collmex selbst kann das AFAIK nicht, aber so etwas ließe sich natürlich implementieren. Es wären weiterhin drei Requests gegen die API, aber zumindest müsste man selbst nicht die Schleife bauen. 

Hältst du das Feature in der beschriebenen Form für sinnvoll?

**Comment by Argee88** [comment]
Okay, etwas schade... die Frage hatte einen Performancehintergrund, aber grundsätzlich fände ich es auch nett, wenn die SDK es auf die Art implementieren würde, wie du gerade beschrieben hast.

Wenn wir schon über neue Features sprechen: Durch dieses CSV-Format kriegt man ja bei vielen Datensätzen immer sowohl die Head- als auch die Bodydaten. Zum Beispiel bei einer Delivery. So wie ich das sehe, sind bis zum 60. Feld nur Kopfdaten und ab Zeile 61 - 67 Bodydaten, die sich tatsächlich verändern. Die SDK könnte solche Daten gleich gruppieren, sodass eine Lieferung so zurückgegeben werden würde:

```php
[
    // felder 1-60
    'products' => [
        // felder 61-67,
        // felder 61-67,
        // felder 61-67,
    ]
]
```

**Comment by Johnny99211** [comment]
Du kannst bei der Abfrage einfach keine ID mitgeben und bekommst dann alle Produkte in einem Request. Diese musst du dann filtern. Collmex selbst wird dies nie implementieren, da sie sehr verschlossen gegenüber solchen Änderungen sind. @mjaschen ich denke, du kannst dieses Issue deshalb schließen.
