### ISSUE TITLE
Preise bei mehreren Preisgruppen

### ISSUE THREAD

**Issue by flowdee** [mjaschen/collmex#7]
Sobald ein Produkt mehrere Preisgruppen hat, bleibt mittels ProductGet das "price"-Feld leer.

<img width="629" alt="bildschirmfoto 2017-01-30 um 16 42 05" src="https://cloud.githubusercontent.com/assets/2278756/22418362/50e3ee8e-e70b-11e6-9b62-266dcdd580ca.png">

Ich habe mal testweise den Typen ProductPriceGet ( [Doku](http://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,daten_importieren_preise), angepasste Dateien siehe Anlage )  implementiert, aber auch da gibt die API keine Datensätze zurück.

Hast du ne Idee @mjaschen ?

[Typen.zip](https://github.com/mjaschen/collmex/files/738528/Typen.zip)

**Comment by mjaschen** [comment]
Auf die Schnelle weiß ich auch nicht weiter, das müsste man mal ausführlich testen.

**Comment by flowdee** [comment]
Hey @Argee88, do you have any idea how to get pricing data for multiple available price groups (see screenshot above) ?

**Comment by Argee88** [comment]
Ich schreib nur bei meinen PRs auf englisch, aber die Antwort ist auf deutsch einfacher...
Ich hab festgestellt, dass bei ProductGet die Standardpreisgruppe zurückgegeben wird.
Lustigerweise kommt (zumindest meiner Erfahrung nach) bei ProductPriceGet nur was zurück wenn für die Standardpreisgruppe etwas hinterlegt ist... ob das aktuelle Datum im Gültigkeitsbereich der Standardpreisgruppe liegen muss, kann ich aus dem Kopf nicht sagen... müsstest du mal ausprobieren ;)
Hoffe, ich konnte dir helfen. Ich arbeite auch erst seit einem Monat mit Collmex, kann sein, dass meine Erfahrungswerte nicht viel Wert sind :)

**Comment by flowdee** [comment]
Ah, war mir nicht sicher ob du Deutsch sprichst 😄 

Hatte da auch bisher noch nicht wirklich die Möglichkeit gesehen, alle Preisgruppen (ohne Abhängigkeiten) einfach abzufragen.
