### ISSUE TITLE
changed_only vs. only_changed

### ISSUE THREAD

**Issue by cryshell** [mjaschen/collmex#9]
Ich bin gerade über folgendes Problem gestolpert: bei der Benennung der Felder für SalesOrderGet hatte ich mich an CustomerGet ortientiert. Hier heißt es "only_changed". Nun hatte ich in meiner Applikation Rechnungen abzufragen und habe aus Gewohnheit das Feld ebenso genannt. Nur war das Ergebnis nicht wie erwartet - denn in InvoiceGet heißt dieses feld "changed_only".

Vorschlag 1: eine einheitliche Benennung. Ich würde "changed_only" favorisieren.

Vorschlag 2: eine Exception sollte ausgeworfen werden, wenn man Attribute benutzt, die im template nicht enthalten sind.

**Comment by mjaschen** [comment]
Hi,

zum Vorschlag 2: ist bereits so implementiert, siehe:

https://github.com/mjaschen/collmex/blob/master/src/Type/AbstractType.php#L126
https://github.com/mjaschen/collmex/blob/master/src/Type/AbstractType.php#L147

Zum Vorschlag 1: Da habe ich nicht aufgepasst und Mist gebaut. Generell ist eine Vereinheitlichung der Feldnamen eine gute Idee. Das Ändern kann zum jetzigen Zeitpunkt aber zu Problemen führen, weil plötzlich existierender Code nicht mehr funktionieren würde. Es müsste zumindest ein Fallback existieren. Jetzt ist die Frage, ob so ein Fallback den Implementierungsaufwand (Erstellen, Testen) und die gestiegene Komplexität (wir müssten ein Mapping von alten zu neuen Feldnamen einführen) wert ist. Eine andere Möglichkeit wäre, es einfach hart zu ändern und die Library dann als neue Major-Version 1.0 zu releasen. Für die 1.0 wollte ich aber unbedingt noch die Type-Collections einführen, die Arbeit daran ist aber noch nicht abgeschlossen.

**Comment by cryshell** [comment]
Vorschlag 1: würde ich auch eher hart ändern mit Major-Version 1.0, auch wenn das noch etwas dauern sollte.

Vorschlag 2: ich habe mir den Code an dieser Stelle noch nicht genau angesehen, aber das hier funktioniert:

$getCustomerType = new CustomerGet(array('customer_id' => '12345', 'foo' => 'bar'));
$collmexResponse = $collmexRequest->send($getCustomerType->getCsv());

Das eigentlich ungültig Feld 'foo' wird einfach ignoriert und ich erhalte die Records für Kunde 12345.

**Comment by mjaschen** [comment]
Danke, ich baue gerade einen Test dafür. Ich mache mal ein eigenes Ticket dafür auf.

**Comment by Argee88** [comment]
Im Zuge einer solchen Umbenennung bin ich auch dafür die Felder "forename" zu "firstname" zu ändern. Da bisher jede Datenbank, mit der ich gearbeitet habe "firstname" benutzt empfinde ich das als intuitiver :)

**Comment by mjaschen** [comment]
Gerne! Keep it coming :-)

**Comment by mjaschen** [comment]
Changes implemented in 2.0.0.
